[package]
name = "traceroute"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
raw-socket  = { path = "../raw-socket" }
pnet = "0.28.0"
dns-lookup = "1.0.8"
rand = "0.8.4"
structopt = { version = "0.3", default-features = false }
anyhow = "1.0.65"
